export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const GET_INGREDIENT_PRICES_START = 'GET_INGREDIENT_PRICES_START';
export const GET_INGREDIENT_PRICES_SUCCESS = 'GET_INGREDIENT_PRICES_SUCCESS';
export const GET_INGREDIENT_PRICES_FAIL = 'GET_INGREDIENT_PRICES_FAIL';

export const POST_ORDER_START = 'POST_ORDER_START';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAIL = 'POST_ORDER_FAIL';

export const GET_ORDERS_START = 'GET_ORDERS_START';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';

export default {
  INIT_INGREDIENTS,
  ADD_INGREDIENT,
  REMOVE_INGREDIENT,
  GET_INGREDIENT_PRICES_START,
  GET_INGREDIENT_PRICES_SUCCESS,
  GET_INGREDIENT_PRICES_FAIL,
  POST_ORDER_START,
  POST_ORDER_SUCCESS,
  POST_ORDER_FAIL,
  GET_ORDERS_START,
  GET_ORDERS_SUCCESS,
  GET_ORDERS_FAIL
};
