export const GET_INGREDIENTS_WITH_PRICE_START = 'GET_INGREDIENTS_WITH_PRICE_START';
export const GET_INGREDIENTS_WITH_PRICE_SUCCESS = 'GET_INGREDIENTS_WITH_PRICE_SUCCESS';
export const GET_INGREDIENTS_WITH_PRICE_FAIL = 'GET_INGREDIENTS_WITH_PRICE_FAIL';

export const POST_ORDER_START = 'POST_ORDER_START';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAIL = 'POST_ORDER_FAIL';

export const GET_ORDERS_START = 'GET_ORDERS_START';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';

export default {
  GET_INGREDIENTS_WITH_PRICE_START,
  GET_INGREDIENTS_WITH_PRICE_SUCCESS,
  GET_INGREDIENTS_WITH_PRICE_FAIL,
  POST_ORDER_START,
  POST_ORDER_SUCCESS,
  POST_ORDER_FAIL,
  GET_ORDERS_START,
  GET_ORDERS_SUCCESS,
  GET_ORDERS_FAIL
};
